# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tony Perkins
tagline:          'Blog of OMSCS at the Georgia Institute of Technology'
url:              http://www.toperkin.github.io/gtblog/
shorturl:         toperkin.github.io/gtblog/

author:
  name:           'Tony Perkins'


paginate:         1



# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'
